---
name: Build and deploy application to S3 and CloudFront
# Workflow dispatch to trigger the workflow with GitHub Actions.
on:
  workflow_dispatch:
    inputs:
      s3-bucket:
        description: 'S3 bucket name'
        required: true
      dist:
        description: 'Directory with the build files'
        required: true
      region:
        description: 'AWS region'
        required: true
      cloudfront-dist-id:
        description: 'CloudFront distribution ID'
        required: true
      github-oidc-role:
        description: 'IAM role ARN to assume with GitHub OIDC token'
        required: true
# Permissions needed to interact with GitHub OIDC token endpoint.
permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    env:
      S3_BUCKET: ${{ github.event.inputs.s3-bucket }}
      DIST: ${{ github.event.inputs.dist }}
      REGION: ${{ github.event.inputs.region }}
      CLOUDFRONT_DIST_ID: ${{ github.event.inputs.cloudfront-dist-id }}
      GITHUB_OIDC_ROLE: ${{ github.event.inputs.github-oidc-role }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials from AWS account
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.GITHUB_OIDC_ROLE }}
          aws-region: ${{ env.REGION }}
      - name: Install dependencies
        run: |
          node --version
          npm ci --production
      - name: Build static website
        run: |
          npm run build
      - name: Copy files to the production website with AWS CLI
        run: |
          aws s3 sync --delete ${{ env.DIST }} s3://${{ env.S3_BUCKET }}
      - name: Create the invalidation for the distribution with AWS CLI
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ env.CLOUDFRONT_DIST_ID }} --paths "/*"